# Nome do projeto
spring.application.name=fit-cultural

# Usa as variáveis que o Docker também está a usar
spring.datasource.url=jdbc:postgresql://ep-dawn-rain-anmwjqwy-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.keepalive-time=30000

# Configurações hibernates
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${JWT_SECRET:10121618Me@FitCultural2026}
server.error.include-stacktrace=on_param